spring:
  liquibase:
    enabled: true
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/veuve_clicquot
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE